# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'batchEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from utils import MyUtils


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(735, 448)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 50, 638, 368))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.line_2 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 8, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 12, 0, 1, 1)
        self.checkBox_joint = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_joint.setFont(font)
        self.checkBox_joint.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_joint, 3, 1, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.checkBox_geometry = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_geometry.setFont(font)
        self.checkBox_geometry.setObjectName("checkBox_geometry")
        self.horizontalLayout_11.addWidget(self.checkBox_geometry)
        self.checkBox_geometry_1 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.checkBox_geometry_1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_geometry_1.setObjectName("checkBox_geometry_1")
        self.horizontalLayout_11.addWidget(self.checkBox_geometry_1)
        self.checkBox_geometry_2 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.checkBox_geometry_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_geometry_2.setObjectName("checkBox_geometry_2")
        self.horizontalLayout_11.addWidget(self.checkBox_geometry_2)
        self.gridLayout.addLayout(self.horizontalLayout_11, 13, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 16, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 14, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setWordWrap(False)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 11, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 4, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setWordWrap(False)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setWordWrap(False)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 7, 0, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 12, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.gridLayoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 18, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.checkBox_color = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_color.setFont(font)
        self.checkBox_color.setObjectName("checkBox_color")
        self.horizontalLayout_16.addWidget(self.checkBox_color)
        self.checkBox_color_1 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.checkBox_color_1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_color_1.setObjectName("radioButton")
        self.horizontalLayout_16.addWidget(self.checkBox_color_1)
        self.checkBox_color_2 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.checkBox_color_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_color_2.setObjectName("checkBox_color_2")
        self.horizontalLayout_16.addWidget(self.checkBox_color_2)
        self.gridLayout.addLayout(self.horizontalLayout_16, 11, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 6, 1, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 8, 1, 1, 1)
        self.checkBox_split = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_split.setFont(font)
        self.checkBox_split.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox_split, 0, 1, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.checkBox_radiate = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_radiate.setFont(font)
        self.checkBox_radiate.setObjectName("checkBox_radiate")
        self.horizontalLayout_15.addWidget(self.checkBox_radiate)
        self.checkBox_radiate_1 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_radiate_1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_radiate_1.setObjectName("checkBox_radiate_1")
        self.horizontalLayout_15.addWidget(self.checkBox_radiate_1)
        self.checkBox_radiate_2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_radiate_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_radiate_2.setObjectName("checkBox_radiate_2")
        self.horizontalLayout_15.addWidget(self.checkBox_radiate_2)
        self.checkBox_radiate_3 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_radiate_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_radiate_3.setObjectName("checkBox_radiate_3")
        self.horizontalLayout_15.addWidget(self.checkBox_radiate_3)
        self.gridLayout.addLayout(self.horizontalLayout_15, 7, 1, 1, 1)
        self.checkBox_combine = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_combine.setFont(font)
        self.checkBox_combine.setObjectName("checkBox_4")
        self.gridLayout.addWidget(self.checkBox_combine, 5, 1, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.checkBox_spectrum = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_spectrum.setFont(font)
        self.checkBox_spectrum.setObjectName("checkBox_spectrum")
        self.horizontalLayout_14.addWidget(self.checkBox_spectrum)
        self.checkBox_spectrum_1 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_spectrum_1.setEnabled(False)
        self.checkBox_spectrum_1.setChecked(True)
        self.checkBox_spectrum_1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_spectrum_1.setObjectName("checkBox_spectrum_1")
        self.horizontalLayout_14.addWidget(self.checkBox_spectrum_1)
        self.checkBox_spectrum_2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_spectrum_2.setEnabled(False)
        self.checkBox_spectrum_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_spectrum_2.setObjectName("checkBox_spectrum_2")
        self.horizontalLayout_14.addWidget(self.checkBox_spectrum_2)
        self.gridLayout.addLayout(self.horizontalLayout_14, 9, 1, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.checkBox_save = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_save.setFont(font)
        self.checkBox_save.setObjectName("checkBox_8")
        self.horizontalLayout_12.addWidget(self.checkBox_save)
        self.comboBox_type = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_type.setEnabled(False)
        self.comboBox_type.setObjectName("comboBox_2")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.horizontalLayout_12.addWidget(self.comboBox_type)
        self.comboBox_files = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_files.setEnabled(False)
        self.comboBox_files.setObjectName("comboBox_3")
        self.comboBox_files.addItem("")
        self.comboBox_files.addItem("")
        self.horizontalLayout_12.addWidget(self.comboBox_files)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setText(MyUtils.saveJoint_addr)
        self.horizontalLayout_12.addWidget(self.lineEdit_2)
        self.pushButton_addr = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_addr.clicked.connect(self.selectDir)
        self.pushButton_addr.setEnabled(False)
        self.pushButton_addr.setObjectName("pushButton_addr_2")
        self.horizontalLayout_12.addWidget(self.pushButton_addr)
        self.gridLayout.addLayout(self.horizontalLayout_12, 15, 1, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 1, 1, 1, 1)
        self.checkBox_ToWindow = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_ToWindow.setFont(font)
        self.checkBox_ToWindow.setObjectName("checkBox_15")
        self.gridLayout.addWidget(self.checkBox_ToWindow, 17, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 10, 1, 1, 1)


        self.colorBg = QtWidgets.QButtonGroup(self)
        self.colorBg.addButton(self.checkBox_color_1, 11)
        self.colorBg.addButton(self.checkBox_color_2, 12)
        self.checkBox_color_1.setEnabled(False)
        self.checkBox_color_2.setEnabled(False)
        self.checkBox_color_1.setChecked(True)

        self.geometryBg = QtWidgets.QButtonGroup(self)
        self.geometryBg.addButton(self.checkBox_geometry_1, 21)
        self.geometryBg.addButton(self.checkBox_geometry_2, 22)
        self.checkBox_geometry_1.setEnabled(False)
        self.checkBox_geometry_2.setEnabled(False)
        self.checkBox_geometry_1.setChecked(True)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.checkBox_joint.setText(_translate("Dialog", "拼接"))
        self.checkBox_geometry.setText(_translate("Dialog", "几何校正"))
        self.checkBox_geometry_1.setText(_translate("Dialog", "参数校正"))
        self.checkBox_geometry_2.setText(_translate("Dialog", "其他"))
        self.label_13.setText(_translate("Dialog", "2C级"))
        self.label_9.setText(_translate("Dialog", "01级"))
        self.label_11.setText(_translate("Dialog", "2A/2B级"))
        self.checkBox_color.setText(_translate("Dialog", "色彩校正"))
        self.checkBox_color_1.setText(_translate("Dialog", "伪彩色"))
        self.checkBox_color_2.setText(_translate("Dialog", "校正"))

        self.checkBox_split.setText(_translate("Dialog", "拆分"))
        self.checkBox_radiate.setText(_translate("Dialog", "辐射校正"))
        self.checkBox_radiate_1.setText(_translate("Dialog", "暗电流"))
        self.checkBox_radiate_1.setChecked(True)
        self.checkBox_radiate_1.setEnabled(False)
        self.checkBox_radiate_2.setText(_translate("Dialog", "相对辐射"))
        self.checkBox_radiate_2.setChecked(True)
        self.checkBox_radiate_2.setEnabled(False)
        self.checkBox_radiate_3.setText(_translate("Dialog", "绝对辐射"))
        self.checkBox_radiate_3.setEnabled(False)
        self.checkBox_combine.setText(_translate("Dialog", "合成"))
        self.checkBox_spectrum.setText(_translate("Dialog", "光谱校正"))
        self.checkBox_spectrum_1.setText(_translate("Dialog", "波长排序"))
        self.checkBox_spectrum_2.setText(_translate("Dialog", "反射率"))
        self.checkBox_save.setText(_translate("Dialog", "保存"))
        self.comboBox_type.setItemText(0, _translate("Dialog", "raw"))
        self.comboBox_type.setItemText(1, _translate("Dialog", "pds4"))
        self.comboBox_files.setItemText(0, _translate("Dialog", "单文件"))
        self.comboBox_files.setItemText(1, _translate("Dialog", "多文件"))
        self.pushButton_addr.setText(_translate("Dialog", "保存位置"))
        self.checkBox_ToWindow.setText(_translate("Dialog", "输出到窗口"))

        self.checkBox_save.toggled.connect(self.saveCheck)
        self.checkBox_color.toggled.connect(self.colorCheck)
        self.checkBox_radiate.toggled.connect(self.radiateCheck)
        self.checkBox_spectrum.toggled.connect(self.spectrumCheck)
        self.checkBox_geometry.toggled.connect(self.geometryCheck)

    def selectDir(self):
        try:
            download_path = QtWidgets.QFileDialog.getExistingDirectory(None, "浏览", "./")
            self.lineEdit_2.setText(download_path)
            MyUtils.saveJoint_addr = download_path
        except Exception as e:
            print(e)

    def saveCheck(self):
        if self.checkBox_save.isChecked():
            self.comboBox_type.setEnabled(True)
            self.comboBox_files.setEnabled(True)
            self.lineEdit_2.setEnabled(True)
            self.pushButton_addr.setEnabled(True)
        else:
            self.comboBox_type.setEnabled(False)
            self.comboBox_files.setEnabled(False)
            self.lineEdit_2.setEnabled(False)
            self.pushButton_addr.setEnabled(False)
        
    def spectrumCheck(self):
        if self.checkBox_spectrum.isChecked():
            self.checkBox_spectrum_1.setEnabled(True)
            self.checkBox_spectrum_2.setEnabled(True)
        else:
            self.checkBox_spectrum_1.setEnabled(False)
            self.checkBox_spectrum_2.setEnabled(False)

    def colorCheck(self):
        if self.checkBox_color.isChecked():
            self.checkBox_color_1.setEnabled(True)
            self.checkBox_color_2.setEnabled(True)
            if self.comboBox_type.count() < 3:
                self.comboBox_type.addItem("jpg")
        else:
            self.checkBox_color_1.setEnabled(False)
            self.checkBox_color_2.setEnabled(False)
            if self.comboBox_type.count()>2:
                self.comboBox_type.removeItem(self.comboBox_type.count()-1)

    def geometryCheck(self):
        if self.checkBox_geometry.isChecked():
            self.checkBox_geometry_1.setEnabled(True)
            self.checkBox_geometry_2.setEnabled(True)
        else:
            self.checkBox_geometry_1.setEnabled(False)
            self.checkBox_geometry_2.setEnabled(False)

    def radiateCheck(self):
        if self.checkBox_radiate.isChecked():
            self.checkBox_radiate_1.setEnabled(True)
            self.checkBox_radiate_2.setEnabled(True)
            self.checkBox_radiate_3.setEnabled(True)
        else:
            self.checkBox_radiate_1.setEnabled(False)
            self.checkBox_radiate_2.setEnabled(False)
            self.checkBox_radiate_3.setEnabled(False)


class BatchEdit(QtWidgets.QDialog, Ui_Dialog):
    def __init__(self, typeString,parent=None):
        super(BatchEdit, self).__init__(parent)
        # 新建的窗口始终位于当前屏幕的最前面
        self.setWindowFlags(QtCore.Qt.WindowStaysOnTopHint)
        # 阻塞父类窗口不能点击
        self.setWindowModality(QtCore.Qt.ApplicationModal)
        self.setFixedSize(735, 448)
        self.setupUi(self)
        self.setWindowTitle(typeString+"文件批处理选项")

        if typeString != "01":
            self.checkBox_split.setChecked(False)
            self.checkBox_split.setEnabled(False)
        else:
            self.checkBox_split.setChecked(True)
            self.checkBox_split.setEnabled(False)

    def getBatchDict(self):
        dic = {}
        dic.update({"splitCheck":self.checkBox_split.isChecked(),
                    "jointCheck":self.checkBox_joint.isChecked(),
                    "combineCheck":self.checkBox_combine.isChecked(),
                    "radiateCheck":self.checkBox_radiate.isChecked(),
                    "darkCurrntCheck":self.checkBox_radiate_1.isChecked(),
                    "relativeRadiateCheck": self.checkBox_radiate_2.isChecked(),
                    "absoluteRadiateCheck": self.checkBox_radiate_3.isChecked(),
                    "spectrumCheck":self.checkBox_spectrum.isChecked(),
                    "wavelengthSortCheck":self.checkBox_spectrum_1.isChecked(),
                    "reflectanceCheck":self.checkBox_spectrum_2.isChecked(),
                    "colorCheck":self.checkBox_color.isChecked(),
                    "colorCorrectSlect":self.colorBg.checkedId(),
                    "geometryCorrectSlect":self.geometryBg.checkedId(),
                    "saveCheck":self.checkBox_save.isChecked(),
                    "saveType":self.comboBox_type.currentText(),
                    "saveFile":self.comboBox_files.currentText(),
                    "saveDirectory":self.lineEdit_2.text(),
                    "ToWindowCheck":self.checkBox_ToWindow.isChecked()
                    })
        return dic


if __name__=="__main__":
    import sys
    from PyQt5.QtWidgets import QApplication, QFileDialog, QFrame

    app = QApplication(sys.argv)
    win = BatchEdit("2A")
    dic = win.getBatchDict()
    for k,v in dic.items():
        print(k,":",v)
    win.show()
    sys.exit(app.exec_())