# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'expandEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore,  QtWidgets
from PyQt5.QtCore import QRegExp
from PyQt5.QtGui import QRegExpValidator


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 246)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 200, 461, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 30, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(90, 60, 21, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(120, 60, 61, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(300, 60, 61, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(260, 60, 31, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(70, 100, 72, 15))
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(120, 130, 61, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(120, 160, 61, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(80, 130, 41, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(80, 160, 41, 16))
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "填充目标："))
        self.label_2.setText(_translate("Dialog", "宽："))
        self.lineEdit.setText(_translate("Dialog", "2048"))
        self.lineEdit_2.setText(_translate("Dialog", "2048"))
        self.label_3.setText(_translate("Dialog", "高："))
        self.label_4.setText(_translate("Dialog", "填充位置："))
        self.lineEdit_3.setText(_translate("Dialog", "0"))
        self.lineEdit_4.setText(_translate("Dialog", "0"))
        self.label_5.setText(_translate("Dialog", "横向："))
        self.label_6.setText(_translate("Dialog", "纵向："))

        self.lineEdit.setValidator(QRegExpValidator(QRegExp("^[0-9]*[1-9][0-9]*$"), self))
        self.lineEdit_2.setValidator(QRegExpValidator(QRegExp("^[0-9]*[1-9][0-9]*$"), self))
        self.lineEdit_3.setValidator(QRegExpValidator(QRegExp("^[0-9]*[1-9][0-9]*$"), self))
        self.lineEdit_4.setValidator(QRegExpValidator(QRegExp("^[0-9]*[1-9][0-9]*$"), self))

class ExpandEdit(QtWidgets.QDialog,Ui_Dialog):
    def __init__(self,parent = None):
        super(ExpandEdit,self).__init__(parent)
        self.setupUi(self)
        self.setWindowTitle("图像填充")

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    win = ExpandEdit()
    win.show()
    sys.exit(app.exec_())
