# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'batchEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from utils.myUtils import MyUtils



class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(558, 287)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 501, 246))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox.setChecked(True)
        self.checkBox.setEnabled(False)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_3.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_3.addWidget(self.radioButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.radioButton_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_4.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout_4.addWidget(self.radioButton_4)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.radioButton_5 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout_6.addWidget(self.radioButton_5)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_6.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.radioButton_6 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_6.setObjectName("radioButton_6")
        self.verticalLayout_2.addWidget(self.radioButton_6)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.radioButton_7 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_7.setObjectName("radioButton_7")
        self.horizontalLayout_7.addWidget(self.radioButton_7)
        self.radioButton_8 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_8.setObjectName("radioButton_8")
        self.horizontalLayout_7.addWidget(self.radioButton_8)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.bg1 = QtWidgets.QButtonGroup(self)
        self.bg1.addButton(self.radioButton,1)
        self.bg1.addButton(self.radioButton_2, 2)
        self.radioButton.setChecked(True)

        self.bg2 = QtWidgets.QButtonGroup(self)
        self.bg2.addButton(self.radioButton_3, 3)
        self.bg2.addButton(self.radioButton_4, 4)
        self.radioButton_3.setChecked(True)

        self.bg3 = QtWidgets.QButtonGroup(self)
        self.bg3.addButton(self.radioButton_5, 5)
        self.bg3.addButton(self.radioButton_6, 6)
        self.radioButton_5.setChecked(True)

        self.bg4 = QtWidgets.QButtonGroup(self)
        self.bg4.addButton(self.radioButton_7, 7)
        self.bg4.addButton(self.radioButton_8, 8)
        self.radioButton_7.setChecked(True)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "自动拼接合成"))
        self.checkBox.setText(_translate("Dialog", "确定"))
        self.label_2.setText(_translate("Dialog", "几何校正方法"))
        self.radioButton.setText(_translate("Dialog", "矫正参数"))
        self.radioButton_2.setText(_translate("Dialog", "其他"))
        self.label_3.setText(_translate("Dialog", "填充方法"))
        self.radioButton_3.setText(_translate("Dialog", "边缘填充"))
        self.radioButton_4.setText(_translate("Dialog", "零填充"))
        self.label_4.setText(_translate("Dialog", "保存"))
        self.radioButton_5.setText(_translate("Dialog", "是"))
        self.pushButton.setText(_translate("Dialog", "保存位置"))
        self.radioButton_6.setText(_translate("Dialog", "否"))
        self.label_5.setText(_translate("Dialog", "在主窗口打开"))
        self.radioButton_7.setText(_translate("Dialog", "是"))
        self.radioButton_8.setText(_translate("Dialog", "否"))

        self.bg3.buttonClicked.connect(self.bg3clicked)
        self.pushButton.clicked.connect(self.selectDir)
        self.lineEdit.setText(MyUtils.saveJoint_addr)

    def selectDir(self):
        try:
            download_path = QtWidgets.QFileDialog.getExistingDirectory(None, "浏览", "./")
            self.lineEdit.setText(download_path)
        except Exception as e:
            print(e)

    def bg3clicked(self):
        if self.bg3.checkedId()==5:
            self.pushButton.setEnabled(True)
            self.lineEdit.setEnabled(True)
        else:
            self.pushButton.setEnabled(False)
            self.lineEdit.setEnabled(False)

class BatchEdit(QtWidgets.QDialog, Ui_Dialog):
    def __init__(self, typeString,parent=None):
        super(BatchEdit, self).__init__(parent)
        # 新建的窗口始终位于当前屏幕的最前面
        self.setWindowFlags(QtCore.Qt.WindowStaysOnTopHint)
        # 阻塞父类窗口不能点击
        self.setWindowModality(QtCore.Qt.ApplicationModal)
        self.setupUi(self)
        self.setWindowTitle(typeString+"文件批处理选项")



    def getBatchDict(self):
        dic = {}
        dic.update({"bg1":self.bg1.checkedId(),"bg2":self.bg2.checkedId(),"bg3":self.bg3.checkedId(),
                   "bg4":self.bg4.checkedId(),"addr":self.lineEdit.text()})
        return dic


if __name__=="__main__":
    import sys
    from PyQt5.QtWidgets import QApplication, QFileDialog

    app = QApplication(sys.argv)
    win = BatchEdit("2B")
    win.show()
    sys.exit(app.exec_())